name: Storybook Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn ci

      - name: Build Storybook
        run: yarn run build-storybook

      - name: Deploy to GitHub Pages
        uses: Dion/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: .out
